### ISSUE TITLE
agent: delay reboot if ongoing interactive sessions

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#115]
This is a followup to https://github.com/coreos/fedora-coreos-tracker/issues/239.

Right now Zincati triggers a reboot in a silent way, which could surprise any logged users while they are in middle of some interactive maintenance.

For better user experience, it should somehow delay the reboot if it notices any active sessions. Current proposal is to count the number of active consoles before finalizing, and introduce a delay if the result is non-zero. This would match locksmith behavior.

Locksmith used to just sleep for a fixed amount of time. A better option to explore here would be implementing the [inhibitor-lock protocol](https://www.freedesktop.org/wiki/Software/systemd/inhibit/).

**Comment by lucab** [comment]
This requires https://github.com/coreos/zincati/issues/114 to be implemented first.

**Comment by openstacker** [comment]
@lucab  Now we(OpenStack Magnum) are using Fedora CoreOS as nodes for k8s cluster. But because of the auto update, we have to totally disable it now to avoid interrupting the k8s bootstrapping.  However, I would like to see a delayed reboot or manual reboot to leave the option to the owner of the server. Looking forward to seeing your thoughts. Cheers.

**Comment by lucab** [comment]
Hi @openstacker! This specific ticket here is not what you are looking for. The topic however has been previously discussed at https://github.com/coreos/fedora-coreos-tracker/issues/147#issuecomment-606526951.

The approaches from there are: 
 1. have a your own first-boot bootstrapping unit to delay `boot-complete.target`
 2. use a temporary [shutdown inhibitor](https://www.freedesktop.org/software/systemd/man/systemd-inhibit.html)
 3. bring your own [reboot manager](https://github.com/coreos/zincati/blob/0.0.6/docs/usage/updates-strategy.md#lock-based-strategy)
 4. write a config fragment with `updates.enabled = false`, then remove it after bootstrapping and restart `zincati.service`
 5. implement and use https://github.com/coreos/zincati/issues/245 (this is not really targeted at your case)

**Comment by jlebon** [comment]
@lucab Re. https://github.com/coreos/zincati/issues/115#issuecomment-645861581, can we document 1 and 2 in https://github.com/coreos/zincati/blob/master/docs/usage/auto-updates.md? This topic came up in the Nest with Fedora Hands-On Lab.

**Comment by kelvinfan001** [comment]
WRT the [inhibitor-lock protocol](https://www.freedesktop.org/wiki/Software/systemd/inhibit/), because there's currently no convenient verb/command for a user to lift the systemd-inhibit lock, and it doesn't seem intuitive for an interactive user to need to "cancel the inhibit and finalize now" in order to reboot into an update, perhaps it would be simpler to match Locksmith behaviour and introduce a delay if there are logged in interactive users. To allow users to be able to manually reboot into an update after they are done with their work, could we include instructions to use `rpm-ostree finalize-update` in the broadcast warning message?
Instead of a `sleep` (as Locksmith does), could we introduce this delay by having a finite number of attempts, with a period of time in between each attempt? For example, to introduce a 5 minute delay, we could have 5 attempts with 1 minute in between attempts. This would allow us to reboot early if users logged out, and also allow us to make sure that when we attempt to reboot, we're are rebooting at a legal time (as defined by the reboot strategy). This should be easy to implement due to the UpdateAgent being a FSM.
@lucab

**Comment by lucab** [comment]
> could we include instructions to use rpm-ostree finalize-update in the broadcast warning message?

That's a bit of a complex UX, let's avoid going that route for now and re-evaluate later on.

> could we introduce this delay by having a finite number of attempts, with a period of time in between each attempt?

:+1: I like this approach of splitting the delay into smaller intervals. If we go granular enough it is maybe enough to avoid the need for a manual finalization procedure.
