### ISSUE TITLE
Use new --skip-branch-check and verify fedora-coreos.stream commit metadata before unlocking

### ISSUE THREAD

**Issue by jlebon** [coreos/zincati#558]
This is the Zincati part of https://github.com/coreos/fedora-coreos-tracker/issues/749. We need to have it start using the new `--skip-branch-check` when calling `rpm-ostree deploy` and also check in the commit metadata that the stream matches the expected output.

See: https://github.com/coreos/fedora-coreos-tracker/issues/749#issuecomment-834801971
See: https://github.com/coreos/fedora-coreos-tracker/issues/749#issuecomment-839947093

**Comment by kelvinfan001** [comment]
Re: https://github.com/coreos/fedora-coreos-tracker/issues/749#issuecomment-839947093, wouldn't it make more sense to check the commit metadata before trying to stage it (i.e. check it at the check updates stage, that way we avoid fully deploying an invalid release)? 
I think checking metadata makes more sense at the check updates stage, since a release with bad metadata isn't a transient error, i.e. we should never deploy and finalize into an update with bad metadata and it won't fix itself over time; there's no point retrying again later, or ever.
So I think https://github.com/coreos/fedora-coreos-tracker/issues/749#issuecomment-834801971 makes more sense to me. Am I overlooking anything here?

**Comment by jlebon** [comment]
I think the rationale there was that the likelihood this happens was so low that it wasn't worth the added complexity of doing a separate `pull --commit-metadata-only` to check the stream. It's more like a final sanity-check before lifting the lock using information we already have on-hand. Though definitely cool with me if we go the `pull --commit-metadata-only` path too!

**Comment by kelvinfan001** [comment]
Ah okay, that also makes sense. I guess I don't fully know how dangerous it is to deploy a commit potentially from some unknown stream, so it seemed a bit weird to me to check _after_ already creating a deployment and writing everything on disk.

**Comment by kelvinfan001** [comment]
Got it, the sanity check is not for any security purposes (since the the super old node should still have the right keys to verify the nearest barrier release that it's trying to update to). The sanity check is in place to address
```
17:01:14 <jlebon> imagine if we somehow screw up the graph, and the node goes from testing to stable. now, from that point on it's extremely difficult to rectify that situation because the node will now be checking the wrong update graph
17:01:29 <jlebon> it's super unlikely, but super bad
```
which is extremely unlikely.
